### ISSUE TITLE
При возврате назад, не отрабатываются «фильтры» на странице лога чата.

### ISSUE THREAD

**Issue by LESHIY-ODESSA** [radio-t/rt-chat#2]
Обнаружил багу на https://chat.radio-t.com/logs/radio-t-691.html

Windows 10, Firefox 73.0.1

Заходим в лог чата, ставим фильтры :

✅ «Оставить сообщения ведущих»
✅ «Оставить сообщения со ссылками»
✅ «Убрать сообщения ботов»

Нажимаем на любой URL, переходим по ссылке, а потом возвращаемся назад и фильтры уже не действуют, хотя всё галочки продолжают стоять.

**Comment by umputun** [comment]
этот репозиторий для другого чата, https://chat.radio-t.com/
